

web: bench serve  --port 8000


socketio: /home/nayem/.config/nvm/versions/node/v18.20.8/bin/node apps/frappe/socketio.js


watch: bench watch


schedule: bench schedule

worker:  bench worker 1>> logs/worker.log 2>> logs/worker.error.log

